serial3v3:
 #http://answers.gazebosim.org/question/5468/gazebo_ros_pkgs-no-p-gain-specified-for-pid-in-positionjointinterface/
 gazebo_ros_control:
   pid_gains:
     base_to_e1_joint: {p: 100.0, i: 0.01, d: 10.0}
     e1_to_e2_joint: {p: 100.0, i: 0.01, d: 10.0}
     e2_to_e3_joint: {p: 100.0, i: 0.01, d: 10.0}
